### ISSUE TITLE
Where's the Antlr code?

### ISSUE THREAD

**Issue by kaby76** [peytonk132/FortIDE#3]
The branch https://github.com/peytonk132/FortIDE/tree/with-antlr doesn't contain any code that refers to Antlr (`mkdir temp; cd temp; git clone https://github.com/peytonk132/FortIDE.git; cd FortIDE; git checkout with-antlr; rm -rf .git; grep . -R -i -e antlr; echo $?`). There's no driver, no runtime, nothing related to Antlr. I looked in the main branch as well.

Please commit and push the code so I can reproduce the errors you were seeing (https://github.com/antlr/antlr4/issues/4674).

**Comment by peytonk132** [comment]
Sorry about that, I don't know what happened there. I pushed it to the `with-antlr`. All should be there except the `antlr4-runtime.lib`. The `antlr4-runtime.dll` file should bein the x64/Debug folder. The runtime headers are in the mainfunc/antlr-runtime and the .h and .cpp files should be in the F90Files.
