### ISSUE TITLE
Error	C4996	'antlr4::dfa::Vocabulary::EMPTY_VOCABULARY': Use the default constructor of Vocabulary instead.	FortIDE	C:\msys64\home\Kenne\FortIDE-orig\mainfunc\antlr-runtime\Vocabulary.cpp	12	

### ISSUE THREAD

**Issue by kaby76** [peytonk132/FortIDE#6]
The code cannot compile with `/sdl` enabled. You need to turn this off.

**Comment by peytonk132** [comment]
I've gone in and fixed it but if you don't mind, what did that do that it was causing an error.

**Comment by kaby76** [comment]
[EMPTY_VOCABULARY](https://github.com/antlr/antlr4/blob/811b7fda58bd14d7f0abc496b6fd651dfa01ed97/runtime/Cpp/runtime/src/Vocabulary.cpp#L12) is a static field of the class, which is declared here: https://github.com/antlr/antlr4/blob/811b7fda58bd14d7f0abc496b6fd651dfa01ed97/runtime/Cpp/runtime/src/Vocabulary.h#L23. The field is defined with an [attribute](https://eel.is/c++draft/dcl.attr.grammar#nt:attribute-specifier) `[[deprecated("Use the default constructor of Vocabulary instead.")]]`, which is recognized by the compiler when the field is actually referenced, whether applied or defining occurrences outside the .h file. So, this is why the compiler outputs the message.

`/sdl` turns the warning into an error. https://learn.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=msvc-170

**Comment by peytonk132** [comment]
oh, ok. Thanks.
