### ISSUE TITLE
MSB8027	Two or more files with the name of Parser.cpp will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are mainfunc\antlr-runtime\Parser.cpp, mainfunc\searchParser\Parser.cpp	

### ISSUE THREAD

**Issue by kaby76** [peytonk132/FortIDE#7]
This is a warning from the compiler. You will likely need to rename your Parser.* files, not the Antlr4 runtime. This, again, is why the Antlr4 runtime should have been in a completely separate project.

**Comment by peytonk132** [comment]
Yeah,  I had run into that previously. I had simply changed the Parser.cpp and Parser.h files in the searchParser folder to s_Parser.* and changed the include in s_Parser.cpp.
